resources:
- name: goof
  type: git
  source:
    uri: https://github.com/aarlaud-playground/goof
    branch: master

jobs:
- name: Install Dependencies
  plan:
  - get: goof
    trigger: true
  - task: build app
    file: goof/build.yml
  - task: install snyk
    file: goof/ci/install_snyk.sh
- name: Snyk Test
  plan:
  - get: goof
    trigger: true
    passed: [Install Dependencies]
  - task: Run Snyk Test
    file: goof/ci/snyk_test.sh
